#!/bin/bash

# Run tests before commit
npm test -- --run

# Run lint before commit
npm run lint

# Run format before commit
npm run prettier

# Run build before commit
npm run build

# Run lint-staged (runs copyright check)
npx lint-staged
